-- 코드를 입력하세요
SELECT B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, 
    SUM(A.PRICE*C.SALES) AS TOTAL_SALES
FROM BOOK A
INNER JOIN AUTHOR B
ON ( B.AUTHOR_ID = A.AUTHOR_ID )
INNER JOIN (
    SELECT BOOK_ID,SUM(SALES) AS "SALES" FROM BOOK_SALES
    WHERE SALES_DATE 
    BETWEEN TO_DATE('2022-01-01','YYYY-MM-DD') 
    AND TO_DATE('2022-01-31','YYYY-MM-DD')
    GROUP BY BOOK_ID
) C
ON ( C.BOOK_ID = A.BOOK_ID )
GROUP BY B.AUTHOR_ID,B.AUTHOR_NAME,A.CATEGORY
ORDER BY B.AUTHOR_ID, A.CATEGORY DESC