-- 코드를 입력하세요
SELECT
    A.CAR_ID,
    A.CAR_TYPE,
    (DAILY_FEE*((100-B.DISCOUNT_RATE)/100))*30 AS FEE 
FROM CAR_RENTAL_COMPANY_CAR A
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
ON (B.CAR_TYPE = A.CAR_TYPE)
WHERE
    A.CAR_ID NOT IN (
        SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE END_DATE > TO_DATE('2022-11-01','YYYY-MM-DD') 
        AND START_DATE < TO_DATE('2022-11-30','YYYY-MM-DD')
    )
    AND A.CAR_TYPE IN ('세단','SUV')
    AND B.DURATION_TYPE = '30일 이상'
    AND (DAILY_FEE*((100-B.DISCOUNT_RATE)/100))*30 BETWEEN 500000 AND 2000000-1
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID