-- 코드를 입력하세요
WITH T AS (
    SELECT DISTINCT 
        A.CAR_ID AS CAR_ID,
        A.CAR_TYPE AS CAR_TYPE,
        (DAILY_FEE*((100-B.DISCOUNT_RATE)/100))*30 AS FEE 
    FROM CAR_RENTAL_COMPANY_CAR A
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
    ON (B.CAR_TYPE = A.CAR_TYPE)
    WHERE
        A.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
 WHERE END_DATE > TO_DATE('2022-11-01','YYYY-MM-DD') AND START_DATE < TO_DATE('2022-11-30','YYYY-MM-DD')) AND
        A.CAR_TYPE IN ('세단','SUV') AND
        B.DURATION_TYPE = '30일 이상'
)

SELECT CAR_ID, CAR_TYPE, FEE FROM T
WHERE 500000 <= FEE AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC


-- SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
-- WHERE END_DATE > TO_DATE('2022-11-01','YYYY-MM-DD') AND START_DATE < TO_DATE('2022-11-30','YYYY-MM-DD')