-- 코드를 입력하세요
SELECT 
    B.HISTORY_ID,
    B.DIFF*(A.DAILY_FEE*((100-NVL(C.DISCOUNT_RATE,0))/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
INNER JOIN 
(SELECT
    HISTORY_ID,
    CAR_ID,
    (END_DATE-START_DATE)+1 AS DIFF,
    CASE 
        WHEN END_DATE-START_DATE < 6 THEN NULL
        WHEN END_DATE-START_DATE < 29 THEN '7일 이상'
        WHEN END_DATE-START_DATE < 89 THEN '30일 이상'
        ELSE '90일 이상'
     END AS TYPE
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) B
ON ( B.CAR_ID = A.CAR_ID )
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
ON ( C.CAR_TYPE = A.CAR_TYPE AND C.DURATION_TYPE = B.TYPE )
WHERE A.CAR_TYPE='트럭'
ORDER BY FEE DESC, HISTORY_ID DESC

-- SELECT
--     HISTORY_ID,
--     CAR_ID,
--     CASE 
--     WHEN END_DATE-START_DATE < 6 THEN NULL
--     WHEN END_DATE-START_DATE < 29 THEN '7일 이상'
--     WHEN END_DATE-START_DATE < 89 THEN '30일 이상'
--     ELSE '90일 이상'
--     END AS TYPE
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY

-- SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
-- SELECT (100-5)/100 FROM DUAL