-- 코드를 입력하세요
SELECT 
    '/home/grep/src/'|| A.BOARD_ID || '/' || B.FILE_ID || B.FILE_NAME 
    || B.FILE_EXT
    AS FILE_PATH
FROM USED_GOODS_BOARD A
INNER JOIN USED_GOODS_FILE B
ON ( B.BOARD_ID = A.BOARD_ID)
WHERE A.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC;
