-- 코드를 입력하세요
SELECT 
    BOOK_ID,
    AUTHOR_NAME,
    TO_CHAR(PUBLISHED_DATE,'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK A
INNER JOIN AUTHOR B
ON ( B.AUTHOR_ID = A.AUTHOR_ID )
WHERE A.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE